 @include('dark.pages.portfolio.single.style_b.section_a_top')
 @include('dark.pages.portfolio.single.style_b.section_b_intro')
 @include('dark.pages.portfolio.single.style_b.section_c_photos')
 @include('dark.pages.portfolio.single.style_b.section_d_intro2')
 @include('dark.pages.portfolio.single.style_b.section_e_vedio')
 @include('dark.pages.portfolio.single.style_b.section_f_next')